config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: { sessions: "owner/sessions" }

  root 'restaurant#index'

  get 'restaurant/new', to: 'restaurant#new'
  post 'restaurant/create'

  get 'restaurants', to: 'restaurant#index'
  get 'restaurant/:id', to: 'restaurant#show' 
  
  get 'restaurant/:id/edit', to:'restaurant#edit'
  post 'restaurant/update'
  
  post 'restaurant/:id/delete', to: 'restaurant#destroy'

  get 'login', to: 'session#new'
  get 'logout', to: 'session#destroy'

end

app/models/Restaurant.rb
class Restaurant < ActiveRecord::Base
	
	validates :name, presence: true
    validates :address, presence: true

	belongs_to :owner
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise 	:database_authenticatable, :registerable,
        	:recoverable, :rememberable, :trackable, :validatable

    validates :name, presence: true
    validates :email, presence: true

	has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
	before_filter :authenticate_owner!
	before_action :authenticate_owner!
	
	def index
		@restaurants = Restaurant.where({owner:current_owner})

		respond_to do | format |
			format.html
			format.json {render :json => @restaurants }
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])

		respond_to do | format |
			format.html
			format.json {render :json => @restaurant }
		end
	end

	def new
	end

	def create
		@restaurant = Restaurant.create(params.require(:restaurant).permit(:name, :owner, :address, :phone_number, :desc));
		@restaurant.owner = current_owner
		if @restaurant.save
			flash[:success] = "Successfully Created."
			redirect_to ({action: :show, id: @restaurant.id})
		else
			flash[:alert] = @restaurant.errors.full_messages.join(", ")

			render :new
		end
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(params.require(:restaurant).permit(:name, :address, :phone_number, :desc))
		redirect_to ({action: :show, id: 1})
	end

	def destroy
		Restaurant.find(params[:id]).destroy
		
		redirect_to ({action: :index})
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restuarant_helper.rb
module RestuarantHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AllEats</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("List",     restaurants_path ) %></li>
        <li><%= link_to("Profile",  edit_owner_registration_path ) %></li>
        <li><%= link_to("Logout",   destroy_owner_session_path, :method => :delete) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AllEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => '/layouts/header'%>
<div class="alert alert-warning" role="alert"><%= alert %></div>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/restaurant/edit.html.erb
<h1>Edit Restaurant</h1>

<%= form_for(:restaurant, :url=> {:action=>'update'}) do |f| %>

	<p>Name:</p> 
	<%= f.text_field(:name) %><br/>
	
	<p>Description:</p> 
	<%= f.text_field(:desc) %><br/>
	
	<p>Address:</p> 
	<%= f.text_field(:address) %><br/>
	
	<p>Phone Number:</p> 
	<%= f.text_field(:phone_number) %><br/><br/>
	
	<%= hidden_field_tag :id, @restaurant.id %>

	<div class="form-buttons">
		<%= submit_tag("Update") %>
	</div>
		
<% end %>

<%= button_to "Back to Restaurant List", {action: :index}, {method: :get} %>

app/views/restaurant/index.html.erb
<h1>List Restaurant</h1>

<table class="restaurant_table table">
<tr>
	<td>Name</td>
	<td>Desc</td>
	<td>Owner</td>
	<td>Address</td>
	<td>Phone Number</td>
</tr>

<%@restaurants.each do |r| %>
	<tr>
		<td><%= r.name %> </td>
		<td><%= r.desc %> </td>
		<td><%= (r.owner.nil?) ? "No Owner" : r.owner.email %> </td>
		<td><%= r.name %> </td>
		<td><%= r.phone_number %> </td>

		<td><%= button_to "Show", 	{action: :show, 	id: r.id}, 	{method: :get} %> </td>
	</tr>
<%end%>

</table>

<%= button_to "Create Restaurant", {:action => :new}, {:method => :get} %>

app/views/restaurant/new.html.erb
<h1>Create Restaurant</h1>

<%= form_for(:restaurant, :url=> {:action=>'create'}) do |f| %>

	<p>Name:</p> 
	<%= f.text_field(:name) %><br/>
	
	<p>Description:</p> 
	<%= f.text_field(:desc) %><br/>
	
	<p>Address:</p> 
	<%= f.text_field(:address) %><br/>
	
	<p>Phone Number:</p> 
	<%= f.text_field(:phone_number) %><br/><br/>

	<div class="form-buttons">
		<%= submit_tag("Create") %>
	</div>
		
<% end %>

<%= button_to "Back to Restaurant List", {action: :index}, {method: :get} %>

app/views/restaurant/show.html.erb
<h1>Show Resturant</h1>
<% address = (@restaurant.address.nil?) ? "United_States" : @restaurant.address.gsub(" ", "_") %>
<img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= address %>&size=640x400&style=element:labels&key=AIzaSyAHp3ZyQ2x2w9_o5calzuyd8nvdNat5nAI" alt="">


<p>Name: <strong><%= @restaurant.name%></strong></p>
<p>Description: <strong><%= @restaurant.desc%></strong></p>
<p>Owner: <strong><%= (@restaurant.owner.nil?)? "No Owner" : @restaurant.owner.email %></strong></p>
<p>Address: <strong><%= @restaurant.address %></strong></p>
<p>Phone Number: <strong><%= @restaurant.phone_number%></strong></p>

<%= button_to "Edit", 	{action: :edit, 	id: @restaurant.id}, 	{method: :get} %>
<%= button_to "Delete", {action: :destroy, 	id: @restaurant.id} %>

<%= button_to "Back to Restaurant List", {action: :index}, {method: :get} %>

app/views/session/new.html.erb
<h1>Login</h1>

<%= form_tag("restaurants", method: "get") do %>
	<div>
		<%= label_tag(:q, "Username:") %>
  		<%= text_field_tag(:q) %>
	</div>

	<div>
  		<%= label_tag(:q, "Password:") %>
  		<%= text_field_tag(:q) %>
	</div>
	
  	<%= submit_tag("Login") %>
<% end %>